name: Release Multi-Platform

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            artifact_name: push_swap
          - target: aarch64-apple-darwin
            os: macos-latest
            artifact_name: push_swap_mac

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Musl Tools (Linux only)
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Build Binary
        run: |
          make superopt N=5
          make release

      - name: Prepare Binary for Upload
        run: |
          mkdir -p out/
          mv ./push_swap out/${{ matrix.artifact_name }}

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: out/${{ matrix.artifact_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
